api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "custom-banner"
handle = "custom-banner"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/targets-overview
#[START custom-banner.config-ext-point]
[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"
export = "checkoutBlock"

[[extensions.targeting]]
target = "purchase.checkout.delivery-address.render-before"
module = "./src/Checkout.jsx"
export = "deliveryAddress"
#[END custom-banner.config-ext-point]

#[START custom-banner.req-properties]
[extensions.settings]
  [[extensions.settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Banner title"
 #[END custom-banner.req-properties]
 #[START custom-banner.optional-properties]
  description = "Enter a title for the banner."
#[END custom-banner.optional-properties]
#[START custom-banner.req-properties]
  [[extensions.settings.fields]]
  key = "description"
  type = "single_line_text_field"
  name = "Banner description"
#[END custom-banner.req-properties]
#[START custom-banner.optional-properties]
  description = "Enter a description for the banner."
#[END custom-banner.optional-properties]
#[START custom-banner.req-properties]
  [[extensions.settings.fields]]
  key = "status"
  type = "single_line_text_field"
  name = "Banner status"
#[END custom-banner.req-properties]
#[START custom-banner.optional-properties]
    [[extensions.settings.fields.validations]]
    name = "choices"
    value = "[\"info\", \"success\", \"warning\", \"critical\"]"
# [END custom-banner.optional-properties]
#[START custom-banner.req-properties]
  [[extensions.settings.fields]]
  key = "collapsible"
  type = "boolean"
  name = "Show collapsible description."
#[END custom-banner.req-properties]
#[START custom-banner.optional-properties]
  description = "Display controls to expand or collapse the banner description."
#[END custom-banner.optional-properties]
