# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "custom-banner"
handle = "custom-banner"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/targets-overview
#[START custom-banner.config-ext-point]
[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"
export = "checkoutBlock"

[[extensions.targeting]]
target = "purchase.checkout.delivery-address.render-before"
module = "./src/Checkout.jsx"
export = "deliveryAddress"
#[END custom-banner.config-ext-point]

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

#[START custom-banner.req-properties]
[extensions.settings]
  [[extensions.settings.fields]]
  key = "trigger_target"
  type = "single_line_text_field"
  name = "Trigger Target"
  description = "Enter a title for the banner (change)"
    [[extensions.settings.fields.validations]]
    name = "choices"
    value = "[\"carrier\"]"
    #description = "Select the attribute of the selected shipping option that should trigger the banner to display"
  [[extensions.settings.fields]]
  key = "trigger_value"
  type = "single_line_text_field"
  name = "Trigger Value"
    [[extensions.settings.fields.validations]]
    name = "choices"
    value = "[\"Canada Post\", \"USPS\", \"UPS\"]"

#[START custom-banner.req-properties]
  [[extensions.settings.fields]]
  key = "description"
  type = "single_line_text_field"
  name = "Banner description"
#[END custom-banner.req-properties]


# 0   description = "Select the value of the attribute that should trigger the banner to display"
