# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "custom-banner-react"
client_id = "e75ce69957548e7633f86e503590fa20"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "dynamic-banner-store-tutorial.myshopify.com"
